export type Severity = "critical" | "high" | "medium" | "low";
export type FixRequestStatus = "pending" | "running" | "completed" | "failed" | "cancelled";

export interface FixRequest {
  id: string;
  repoId: string;
  scanId: string;
  fixes: string[];
  status: FixRequestStatus;
  branchName: string;
  prNumber: number | null;
  prUrl: string | null;
  errorMessage: string | null;
  estFilesAdded: number;
  estFilesChanged: number;
  estDeps: number;
  creditsCost: number;
  createdAt: string;
}

export interface Issue {
  id: string;
  category: string;
  title: string;
  severity: Severity;
  why: string;
  timeSaved: string; // e.g. "2h"
  fixId: string;
}

export interface Repo {
  id: string;
  name: string;
  full_name: string;
  description: string;
  language: string;
  stars: number;
  updated: string;
  private: boolean;
  framework: "Next.js" | "React Vite" | "Express";
}

export interface Scan {
  id: string;
  repoId: string;
  score: number;
  createdAt: string;
  issues: Issue[];
}

export const MOCK_REPOS: Repo[] = [
  { id: "r1", name: "nextjs-saas-app", full_name: "demo/nextjs-saas-app", description: "Next.js SaaS App — auth, billing, dashboard", language: "TypeScript", stars: 42, updated: "2 hours ago", private: false, framework: "Next.js" },
  { id: "r2", name: "react-vite-dashboard", full_name: "demo/react-vite-dashboard", description: "React Vite Dashboard — analytics & charts", language: "TypeScript", stars: 18, updated: "yesterday", private: true, framework: "React Vite" },
  { id: "r3", name: "express-api-server", full_name: "demo/express-api-server", description: "Express API Server — REST endpoints + Postgres", language: "JavaScript", stars: 7, updated: "3 days ago", private: true, framework: "Express" },
];

const COMMON_ISSUES = (framework: Repo["framework"]): Issue[] => [
  { id: "i-vitest", fixId: "vitest", category: "Testing", title: "No unit test framework configured", severity: "high", why: "Without tests, regressions slip into production. Vitest gives instant feedback.", timeSaved: "3h" },
  { id: "i-playwright", fixId: "playwright", category: "Testing", title: "Missing end-to-end tests", severity: "medium", why: "E2E tests catch broken user flows before users do.", timeSaved: "4h" },
  { id: "i-ci", fixId: "github-actions", category: "CI/CD", title: "No GitHub Actions workflow", severity: "critical", why: "Every push should run lint, typecheck, and tests automatically.", timeSaved: "2h" },
  { id: "i-eslint", fixId: "eslint", category: "Code Quality", title: "ESLint not configured", severity: "high", why: "Catches bugs and enforces consistent style across contributors.", timeSaved: "1h" },
  { id: "i-prettier", fixId: "prettier", category: "Code Quality", title: "Prettier not configured", severity: "low", why: "Removes formatting debates and makes diffs clean.", timeSaved: "30m" },
  { id: "i-env", fixId: "env-example", category: "Security", title: "Missing .env.example", severity: "high", why: "Contributors can't run your app without knowing required env vars.", timeSaved: "1h" },
  { id: "i-docker", fixId: "dockerfile", category: "Deployment", title: framework === "Express" ? "No Dockerfile for backend" : "No Dockerfile", severity: "medium", why: "Reproducible builds for any deployment target.", timeSaved: "2h" },
  { id: "i-readme", fixId: "readme", category: "Documentation", title: "README missing setup section", severity: "medium", why: "Onboarding new devs (or your future self) takes hours without it.", timeSaved: "1h" },
  { id: "i-monitor", fixId: "monitoring", category: "Monitoring", title: "No error monitoring (Sentry)", severity: "high", why: "You won't know production crashes happened until users complain.", timeSaved: "2h" },
];

export const MOCK_SCANS: Record<string, Scan> = Object.fromEntries(
  MOCK_REPOS.map((r) => {
    const issues = COMMON_ISSUES(r.framework);
    // score: 100 minus weighted issues
    const weights: Record<Severity, number> = { critical: 12, high: 7, medium: 4, low: 2 };
    const score = Math.max(20, 100 - issues.reduce((s, i) => s + weights[i.severity], 0));
    return [r.id, { id: `s-${r.id}`, repoId: r.id, score, createdAt: "just now", issues }];
  })
);

export const RECENT_SCANS = [
  { repo: "demo/nextjs-saas-app", score: 62, when: "2h ago" },
  { repo: "demo/react-vite-dashboard", score: 48, when: "yesterday" },
  { repo: "demo/express-api-server", score: 55, when: "3 days ago" },
];

export type DiffLine = { type: "add" | "del" | "ctx" | "hunk"; text: string; oldNo?: number; newNo?: number };
export type FileDiff = { path: string; status: "added" | "modified"; lines: DiffLine[] };

export interface FixPreview {
  files_added: string[];
  files_changed: string[];
  deps: string[];
  diffs: FileDiff[];
  creditCost?: number; // 0 for template fixes; AI fixes will set a positive value
  isAi?: boolean;      // true = content generated by Claude at job time, diffs are illustrative
}

const add = (text: string, newNo: number): DiffLine => ({ type: "add", text, newNo });
const ctx = (text: string, oldNo: number, newNo: number): DiffLine => ({ type: "ctx", text, oldNo, newNo });
const hunk = (text: string): DiffLine => ({ type: "hunk", text });

export const FIX_DETAILS: Record<string, FixPreview & { label: string }> = {
  vitest: {
    label: "Add Vitest",
    files_added: ["vitest.config.ts", "tests/smoke.test.ts"],
    files_changed: ["package.json"],
    deps: ["vitest", "@vitejs/plugin-react"],
    diffs: [
      {
        path: "vitest.config.ts",
        status: "added",
        lines: [
          hunk("@@ -0,0 +1,10 @@"),
          add(`import { defineConfig } from "vitest/config";`, 1),
          add(`import react from "@vitejs/plugin-react";`, 2),
          add(``, 3),
          add(`export default defineConfig({`, 4),
          add(`  plugins: [react()],`, 5),
          add(`  test: {`, 6),
          add(`    environment: "jsdom",`, 7),
          add(`    globals: true,`, 8),
          add(`  },`, 9),
          add(`});`, 10),
        ],
      },
      {
        path: "tests/smoke.test.ts",
        status: "added",
        lines: [
          hunk("@@ -0,0 +1,7 @@"),
          add(`import { describe, it, expect } from "vitest";`, 1),
          add(``, 2),
          add(`describe("smoke", () => {`, 3),
          add(`  it("runs without error", () => {`, 4),
          add(`    expect(true).toBe(true);`, 5),
          add(`  });`, 6),
          add(`});`, 7),
        ],
      },
      {
        path: "package.json",
        status: "modified",
        lines: [
          hunk("@@ -8,4 +8,7 @@"),
          ctx(`  "scripts": {`, 8, 8),
          ctx(`    "dev": "vite",`, 9, 9),
          ctx(`    "build": "vite build",`, 10, 10),
          add(`    "test": "vitest",`, 11),
          add(`    "test:ui": "vitest --ui",`, 12),
          add(`    "test:coverage": "vitest run --coverage",`, 13),
          ctx(`  },`, 11, 14),
        ],
      },
    ],
  },
  playwright: {
    label: "Add Playwright",
    files_added: ["playwright.config.ts", "e2e/home.spec.ts"],
    files_changed: ["package.json", ".gitignore"],
    deps: ["@playwright/test"],
    diffs: [
      {
        path: "e2e/home.spec.ts",
        status: "added",
        lines: [
          hunk("@@ -0,0 +1,6 @@"),
          add(`import { test, expect } from "@playwright/test";`, 1),
          add(``, 2),
          add(`test("home loads", async ({ page }) => {`, 3),
          add(`  await page.goto("/");`, 4),
          add(`  await expect(page).toHaveTitle(/./);`, 5),
          add(`});`, 6),
        ],
      },
      {
        path: ".gitignore",
        status: "modified",
        lines: [
          hunk("@@ -10,2 +10,5 @@"),
          ctx(`node_modules`, 10, 10),
          ctx(`dist`, 11, 11),
          add(`/test-results/`, 12),
          add(`/playwright-report/`, 13),
          add(`/playwright/.cache/`, 14),
        ],
      },
    ],
  },
  "github-actions": {
    label: "Add GitHub Actions CI",
    files_added: [".github/workflows/ci.yml"],
    files_changed: [],
    deps: [],
    diffs: [
      {
        path: ".github/workflows/ci.yml",
        status: "added",
        lines: [
          hunk("@@ -0,0 +1,62 @@"),
          add(`name: CI`, 1),
          add(``, 2),
          add(`on:`, 3),
          add(`  push:`, 4),
          add(`  pull_request:`, 5),
          add(``, 6),
          add(`jobs:`, 7),
          add(`  ci:`, 8),
          add(`    runs-on: ubuntu-latest`, 9),
          add(`    steps:`, 10),
          add(`      - uses: actions/checkout@v4`, 11),
          add(``, 12),
          add(`      - name: Detect package manager`, 13),
          add(`        id: pm`, 14),
          add(`        run: |`, 15),
          add(`          if [ -f pnpm-lock.yaml ]; then`, 16),
          add(`            echo "name=pnpm"                              >> $GITHUB_OUTPUT`, 17),
          add(`            echo "install=pnpm install --frozen-lockfile" >> $GITHUB_OUTPUT`, 18),
          add(`            echo "run=pnpm run"                           >> $GITHUB_OUTPUT`, 19),
          add(`          elif [ -f yarn.lock ]; then`, 20),
          add(`            echo "name=yarn"                              >> $GITHUB_OUTPUT`, 21),
          add(`            echo "install=yarn install --frozen-lockfile" >> $GITHUB_OUTPUT`, 22),
          add(`            echo "run=yarn"                               >> $GITHUB_OUTPUT`, 23),
          add(`          else`, 24),
          add(`            echo "name=npm"                               >> $GITHUB_OUTPUT`, 25),
          add(`            echo "install=npm ci"                         >> $GITHUB_OUTPUT`, 26),
          add(`            echo "run=npm run"                            >> $GITHUB_OUTPUT`, 27),
          add(`          fi`, 28),
          add(``, 29),
          add(`      - name: Setup pnpm`, 30),
          add(`        if: steps.pm.outputs.name == 'pnpm'`, 31),
          add(`        uses: pnpm/action-setup@v4`, 32),
          add(`        with:`, 33),
          add(`          run_install: false`, 34),
          add(``, 35),
          add(`      - uses: actions/setup-node@v4`, 36),
          add(`        with:`, 37),
          add(`          node-version: 20`, 38),
          add(`          cache: \${{ steps.pm.outputs.name }}`, 39),
          add(``, 40),
          add(`      - name: Install dependencies`, 41),
          add(`        run: \${{ steps.pm.outputs.install }}`, 42),
          add(``, 43),
          add(`      - name: Check scripts`, 44),
          add(`        id: scripts`, 45),
          add(`        run: |`, 46),
          add(`          has() { node -e "process.exit(require('./package.json').scripts?.['$1'] ? 0 : 1)"; }`, 47),
          add(`          has lint  && echo "lint=true"  >> $GITHUB_OUTPUT || echo "lint=false"  >> $GITHUB_OUTPUT`, 48),
          add(`          has test  && echo "test=true"  >> $GITHUB_OUTPUT || echo "test=false"  >> $GITHUB_OUTPUT`, 49),
          add(`          has build && echo "build=true" >> $GITHUB_OUTPUT || echo "build=false" >> $GITHUB_OUTPUT`, 50),
          add(``, 51),
          add(`      - name: Lint`, 52),
          add(`        if: steps.scripts.outputs.lint == 'true'`, 53),
          add(`        run: \${{ steps.pm.outputs.run }} lint`, 54),
          add(``, 55),
          add(`      - name: Test`, 56),
          add(`        if: steps.scripts.outputs.test == 'true'`, 57),
          add(`        run: \${{ steps.pm.outputs.run }} test`, 58),
          add(``, 59),
          add(`      - name: Build`, 60),
          add(`        if: steps.scripts.outputs.build == 'true'`, 61),
          add(`        run: \${{ steps.pm.outputs.run }} build`, 62),
        ],
      },
    ],
  },
  eslint: {
    label: "Add ESLint config",
    files_added: ["eslint.config.js"],
    files_changed: ["package.json"],
    deps: ["eslint", "@typescript-eslint/parser", "@typescript-eslint/eslint-plugin"],
    diffs: [
      {
        path: "eslint.config.js",
        status: "added",
        lines: [
          hunk("@@ -0,0 +1,8 @@"),
          add(`import tseslint from "@typescript-eslint/eslint-plugin";`, 1),
          add(`import parser from "@typescript-eslint/parser";`, 2),
          add(``, 3),
          add(`export default [{`, 4),
          add(`  files: ["**/*.{ts,tsx}"],`, 5),
          add(`  languageOptions: { parser },`, 6),
          add(`  plugins: { "@typescript-eslint": tseslint },`, 7),
          add(`}];`, 8),
        ],
      },
    ],
  },
  prettier: {
    label: "Add Prettier",
    files_added: [".prettierrc", ".prettierignore"],
    files_changed: ["package.json"],
    deps: ["prettier"],
    diffs: [
      {
        path: ".prettierrc",
        status: "added",
        lines: [
          hunk("@@ -0,0 +1,6 @@"),
          add(`{`, 1),
          add(`  "semi": true,`, 2),
          add(`  "singleQuote": false,`, 3),
          add(`  "trailingComma": "all",`, 4),
          add(`  "printWidth": 100`, 5),
          add(`}`, 6),
        ],
      },
    ],
  },
  dockerfile: {
    label: "Add Dockerfile",
    files_added: ["Dockerfile", ".dockerignore"],
    files_changed: [],
    deps: [],
    diffs: [
      {
        path: "Dockerfile",
        status: "added",
        lines: [
          hunk("@@ -0,0 +1,11 @@"),
          add(`FROM node:20-alpine AS build`, 1),
          add(`WORKDIR /app`, 2),
          add(`COPY package*.json ./`, 3),
          add(`RUN npm ci`, 4),
          add(`COPY . .`, 5),
          add(`RUN npm run build`, 6),
          add(``, 7),
          add(`FROM node:20-alpine`, 8),
          add(`WORKDIR /app`, 9),
          add(`COPY --from=build /app ./`, 10),
          add(`CMD ["npm", "start"]`, 11),
        ],
      },
    ],
  },
  "env-example": {
    label: "Add .env.example",
    files_added: [".env.example"],
    files_changed: ["README.md"],
    deps: [],
    diffs: [
      {
        path: ".env.example",
        status: "added",
        lines: [
          hunk("@@ -0,0 +1,5 @@"),
          add(`# Copy to .env and fill in`, 1),
          add(`DATABASE_URL=`, 2),
          add(`NEXTAUTH_SECRET=`, 3),
          add(`STRIPE_SECRET_KEY=`, 4),
          add(`SENTRY_DSN=`, 5),
        ],
      },
    ],
  },
  readme: {
    label: "Add README setup section",
    files_added: [],
    files_changed: ["README.md"],
    deps: [],
    diffs: [
      {
        path: "README.md",
        status: "modified",
        lines: [
          hunk("@@ -1,1 +1,46 @@"),
          ctx(`# project-name`, 1, 1),
          add(``, 2),
          add(`## Getting started`, 3),
          add(``, 4),
          add(`**1. Clone and install**`, 5),
          add(``, 6),
          add(`\`\`\`bash`, 7),
          add(`git clone https://github.com/<you>/project-name.git`, 8),
          add(`cd project-name`, 9),
          add(`npm install`, 10),
          add(`\`\`\``, 11),
          add(``, 12),
          add(`**2. Configure environment**`, 13),
          add(``, 14),
          add(`\`\`\`bash`, 15),
          add(`cp .env.example .env`, 16),
          add(`\`\`\``, 17),
          add(``, 18),
          add(`Fill in \`.env\` with required variables. See \`.env.example\` for details.`, 19),
          add(``, 20),
          add(`**3. Run in development**`, 21),
          add(``, 22),
          add(`\`\`\`bash`, 23),
          add(`npm run dev`, 24),
          add(`\`\`\``, 25),
          add(``, 26),
          add(`## Build`, 27),
          add(``, 28),
          add(`\`\`\`bash`, 29),
          add(`npm run build`, 30),
          add(`npm start`, 31),
          add(`\`\`\``, 32),
          add(``, 33),
          add(`## Test`, 34),
          add(``, 35),
          add(`\`\`\`bash`, 36),
          add(`npm test`, 37),
          add(`\`\`\``, 38),
          add(``, 39),
          add(`## Deployment`, 40),
          add(``, 41),
          add(`Set the environment variables from \`.env.example\` on your host,`, 42),
          add(`then run the build and start commands above.`, 43),
        ],
      },
    ],
  },
  monitoring: {
    label: "Add error monitoring (Sentry)",
    files_added: ["src/lib/sentry.ts"],
    files_changed: ["src/main.tsx", "package.json"],
    deps: ["@sentry/react"],
    diffs: [
      {
        path: "src/lib/sentry.ts",
        status: "added",
        lines: [
          hunk("@@ -0,0 +1,6 @@"),
          add(`import * as Sentry from "@sentry/react";`, 1),
          add(``, 2),
          add(`Sentry.init({`, 3),
          add(`  dsn: import.meta.env.VITE_SENTRY_DSN,`, 4),
          add(`  tracesSampleRate: 0.1,`, 5),
          add(`});`, 6),
        ],
      },
      {
        path: "src/main.tsx",
        status: "modified",
        lines: [
          hunk("@@ -1,3 +1,4 @@"),
          ctx(`import React from "react";`, 1, 1),
          ctx(`import ReactDOM from "react-dom/client";`, 2, 2),
          add(`import "./lib/sentry";`, 3),
          ctx(`import App from "./App";`, 3, 4),
        ],
      },
    ],
  },
  helmet: {
    label: "Add Helmet (security headers)",
    files_added: ["src/middleware/security.ts"],
    files_changed: ["src/index.ts"],
    deps: ["helmet"],
    diffs: [
      {
        path: "src/middleware/security.ts",
        status: "added",
        lines: [
          hunk("@@ -0,0 +1,6 @@"),
          add(`import helmet from "helmet";`, 1),
          add(`import type { Express } from "express";`, 2),
          add(``, 3),
          add(`export function applyHelmet(app: Express): void {`, 4),
          add(`  app.use(helmet());`, 5),
          add(`}`, 6),
        ],
      },
      {
        path: "src/index.ts",
        status: "modified",
        lines: [
          hunk("@@ -1,3 +1,5 @@"),
          ctx(`import express from "express";`, 1, 1),
          add(`import { applyHelmet } from "./middleware/security";`, 2),
          ctx(``, 2, 3),
          ctx(`const app = express();`, 3, 4),
          add(`applyHelmet(app);`, 5),
        ],
      },
    ],
  },
  "rate-limit": {
    label: "Add rate limiting",
    files_added: ["src/middleware/rate-limit.ts"],
    files_changed: ["src/index.ts"],
    deps: ["express-rate-limit"],
    diffs: [
      {
        path: "src/middleware/rate-limit.ts",
        status: "added",
        lines: [
          hunk("@@ -0,0 +1,13 @@"),
          add(`import rateLimit from "express-rate-limit";`, 1),
          add(`import type { Express } from "express";`, 2),
          add(``, 3),
          add(`const limiter = rateLimit({`, 4),
          add(`  windowMs: 15 * 60 * 1000,`, 5),
          add(`  max: 100,`, 6),
          add(`  standardHeaders: true,`, 7),
          add(`  legacyHeaders: false,`, 8),
          add(`});`, 9),
          add(``, 10),
          add(`export function applyRateLimit(app: Express): void {`, 11),
          add(`  app.use(limiter);`, 12),
          add(`}`, 13),
        ],
      },
      {
        path: "src/index.ts",
        status: "modified",
        lines: [
          hunk("@@ -1,3 +1,5 @@"),
          ctx(`import express from "express";`, 1, 1),
          add(`import { applyRateLimit } from "./middleware/rate-limit";`, 2),
          ctx(``, 2, 3),
          ctx(`const app = express();`, 3, 4),
          add(`applyRateLimit(app);`, 5),
        ],
      },
    ],
  },
  "vitest-ai": {
    label: "Vitest — AI-generated tests",
    files_added: ["tests/unit.test.ts"],
    files_changed: [],
    deps: ["vitest", "@vitejs/plugin-react"],
    creditCost: 2,
    isAi: true,
    diffs: [
      {
        path: "tests/unit.test.ts",
        status: "added",
        lines: [
          hunk("@@ -0,0 +1,1 @@"),
          add(`// Generated by Claude based on your actual source files`, 1),
        ],
      },
    ],
  },
  "playwright-ai": {
    label: "Playwright — AI-generated E2E tests",
    files_added: ["e2e/main.spec.ts"],
    files_changed: [],
    deps: ["@playwright/test"],
    creditCost: 2,
    isAi: true,
    diffs: [
      {
        path: "e2e/main.spec.ts",
        status: "added",
        lines: [
          hunk("@@ -0,0 +1,1 @@"),
          add(`// Generated by Claude based on your actual routes`, 1),
        ],
      },
    ],
  },
  "api-tests": {
    label: "API tests — AI-generated (Supertest)",
    files_added: ["tests/api.test.ts"],
    files_changed: [],
    deps: ["supertest", "@types/supertest"],
    creditCost: 2,
    isAi: true,
    diffs: [
      {
        path: "tests/api.test.ts",
        status: "added",
        lines: [
          hunk("@@ -0,0 +1,1 @@"),
          add(`// Generated by Claude based on your Express routes`, 1),
        ],
      },
    ],
  },
  logger: {
    label: "Add request logger (Winston)",
    files_added: ["src/lib/logger.ts", "src/middleware/logging.ts"],
    files_changed: ["src/index.ts"],
    deps: ["winston"],
    diffs: [
      {
        path: "src/lib/logger.ts",
        status: "added",
        lines: [
          hunk("@@ -0,0 +1,10 @@"),
          add(`import winston from "winston";`, 1),
          add(``, 2),
          add(`export const logger = winston.createLogger({`, 3),
          add(`  level: process.env.LOG_LEVEL ?? "info",`, 4),
          add(`  format: winston.format.combine(`, 5),
          add(`    winston.format.timestamp(),`, 6),
          add(`    winston.format.json(),`, 7),
          add(`  ),`, 8),
          add(`  transports: [new winston.transports.Console()],`, 9),
          add(`});`, 10),
        ],
      },
      {
        path: "src/middleware/logging.ts",
        status: "added",
        lines: [
          hunk("@@ -0,0 +1,15 @@"),
          add(`import type { Request, Response, NextFunction } from "express";`, 1),
          add(`import { logger } from "../lib/logger";`, 2),
          add(``, 3),
          add(`export function requestLogger(req: Request, res: Response, next: NextFunction) {`, 4),
          add(`  const start = Date.now();`, 5),
          add(`  res.on("finish", () => {`, 6),
          add(`    logger.info("request", {`, 7),
          add(`      method: req.method,`, 8),
          add(`      url: req.url,`, 9),
          add(`      status: res.statusCode,`, 10),
          add(`      ms: Date.now() - start,`, 11),
          add(`    });`, 12),
          add(`  });`, 13),
          add(`  next();`, 14),
          add(`}`, 15),
        ],
      },
      {
        path: "src/index.ts",
        status: "modified",
        lines: [
          hunk("@@ -1,3 +1,5 @@"),
          ctx(`import express from "express";`, 1, 1),
          add(`import { requestLogger } from "./middleware/logging";`, 2),
          ctx(``, 2, 3),
          ctx(`const app = express();`, 3, 4),
          add(`app.use(requestLogger);`, 5),
        ],
      },
    ],
  },
};
