name = "launch-ready"
compatibility_date = "2026-06-06"
compatibility_flags = [ "nodejs_compat", "nodejs_compat_populate_process_env" ]
main = "src/server.ts"

[observability]
enabled = true

[assets]
directory = "dist/client"
binding = "ASSETS"
