/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepoRepoIdRouteImport } from './routes/repo.$repoId'
import { Route as PrRepoIdRouteImport } from './routes/pr.$repoId'
import { Route as RepoRepoIdFixRouteImport } from './routes/repo.$repoId.fix'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoRepoIdRoute = RepoRepoIdRouteImport.update({
  id: '/repo/$repoId',
  path: '/repo/$repoId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrRepoIdRoute = PrRepoIdRouteImport.update({
  id: '/pr/$repoId',
  path: '/pr/$repoId',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoRepoIdFixRoute = RepoRepoIdFixRouteImport.update({
  id: '/fix',
  path: '/fix',
  getParentRoute: () => RepoRepoIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pr/$repoId': typeof PrRepoIdRoute
  '/repo/$repoId': typeof RepoRepoIdRouteWithChildren
  '/repo/$repoId/fix': typeof RepoRepoIdFixRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pr/$repoId': typeof PrRepoIdRoute
  '/repo/$repoId': typeof RepoRepoIdRouteWithChildren
  '/repo/$repoId/fix': typeof RepoRepoIdFixRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pr/$repoId': typeof PrRepoIdRoute
  '/repo/$repoId': typeof RepoRepoIdRouteWithChildren
  '/repo/$repoId/fix': typeof RepoRepoIdFixRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/pr/$repoId'
    | '/repo/$repoId'
    | '/repo/$repoId/fix'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/pr/$repoId' | '/repo/$repoId' | '/repo/$repoId/fix'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/pr/$repoId'
    | '/repo/$repoId'
    | '/repo/$repoId/fix'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  PrRepoIdRoute: typeof PrRepoIdRoute
  RepoRepoIdRoute: typeof RepoRepoIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/$repoId': {
      id: '/repo/$repoId'
      path: '/repo/$repoId'
      fullPath: '/repo/$repoId'
      preLoaderRoute: typeof RepoRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pr/$repoId': {
      id: '/pr/$repoId'
      path: '/pr/$repoId'
      fullPath: '/pr/$repoId'
      preLoaderRoute: typeof PrRepoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repo/$repoId/fix': {
      id: '/repo/$repoId/fix'
      path: '/fix'
      fullPath: '/repo/$repoId/fix'
      preLoaderRoute: typeof RepoRepoIdFixRouteImport
      parentRoute: typeof RepoRepoIdRoute
    }
  }
}

interface RepoRepoIdRouteChildren {
  RepoRepoIdFixRoute: typeof RepoRepoIdFixRoute
}

const RepoRepoIdRouteChildren: RepoRepoIdRouteChildren = {
  RepoRepoIdFixRoute: RepoRepoIdFixRoute,
}

const RepoRepoIdRouteWithChildren = RepoRepoIdRoute._addFileChildren(
  RepoRepoIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  PrRepoIdRoute: PrRepoIdRoute,
  RepoRepoIdRoute: RepoRepoIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
